development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tracker_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tracker_test
  pool: 5
  username: root
  password: